### ISSUE TITLE
`elba build` fail when depending on C FFI

### ISSUE THREAD

**Issue by andrevidela** [elba/elba#54]
Hi there,

I have a project which compiles a .c source and exposes it in idris using `%include C` and `%link C`.

I used a script in order to compile the file and output the object file like so:

```toml
[scripts]
"prebuild" = "cc -O2 -c -o array.o array.c `idris --include`"
```

However `elba build` fails with the following error:

```
> "idris" "--check" "Data/Bytes.idr" "Data/ByteArray.idr"
 user error (Can't find file array.o)
```

Interestingly enough compiling in the current folder with

```
idris --check Data/Bytes.idr Data/ByteArray.idr
```

works perfectly fine.

Am I missing something or is this use case not supported?
