### ISSUE TITLE
repl command does not respect idris_opts

### ISSUE THREAD

**Issue by karroffel** [elba/elba#73]
I have a project which uses the `contrib` package.

```toml
[targets.lib]
path = "src"
mods = [
    # ...
]
idris_opts = ["-p", "contrib"]
```

Building with elba works nicely and the package is added, however when I run `elba repl` it does not add the `-p contrib` to the Idris command causing there to be an error when loading my files.

Maybe elba can append the command line options to the repl invokation to resolve this?

**Comment by andylokandy** [comment]
You may want this: 

```toml
[targets.lib]
path = "src"
mods = [ ... ]
idris_opts = ["-p", "contrib", "-p", "effects"]
```

**Comment by karroffel** [comment]
At the moment I have this and this does not work: 

```toml
[targets.lib]
path = "src"
mods = [
    "Network.Http.Server"
]
idris_opts = ["-p", "contrib"]
```
Adding the effects package does not work, neither does removing test configurations or commenting out the module.
